### ISSUE TITLE
Pyspark Error: java.lang.NoSuchMethodError: 'scala.collection.immutable.ArraySeq 

### ISSUE THREAD

**Issue by esadler-hbo** [pinecone-io/spark-pinecone#4]
I am getting the following error and I am not a scala / java dev. Hopefully, someone here could point me in the right direction!

This is what I have tried:
1. I tried running my code locally, but couldn't get it to work even after lining up the spark, scala, and java versions. 
2. I tried running it from inside a pyspark docker image to better control the versions: https://hub.docker.com/r/jupyter/pyspark-notebook:spark-3.2.0.

I am going to try and see if it works from scala next. 

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Input In [5], in <module>
      2 df = pd.DataFrame({
      3     "id": ["1"],
      4     "values": [np.zeros(2048, dtype=np.float32).tolist()],
      5     "namespace": [None],
      6     "metadata": [None]
      7 })
      8 df = spark.createDataFrame(df, schema=schema)
---> 10 (df.write
     11     .option("pinecone.apiKey", PINECONE_API_TOKEN)
     12     .option("pinecone.environment", ENV)
     13     .option("pinecone.projectName", PROJECT_NAME)
     14     .option("pinecone.indexName", INDEX_NAME)
     15     .format("io.pinecone.spark.pinecone.Pinecone")
     16     .mode("append")
     17     .save())

File /usr/local/spark/python/pyspark/sql/readwriter.py:738, in DataFrameWriter.save(self, path, format, mode, partitionBy, **options)
    736     self.format(format)
    737 if path is None:
--> 738     self._jwrite.save()
    739 else:
    740     self._jwrite.save(path)

File /usr/local/spark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py:1309, in JavaMember.__call__(self, *args)
   1303 command = proto.CALL_COMMAND_NAME +\
   1304     self.command_header +\
   1305     args_command +\
   1306     proto.END_COMMAND_PART
   1308 answer = self.gateway_client.send_command(command)
-> 1309 return_value = get_return_value(
   1310     answer, self.gateway_client, self.target_id, self.name)
   1312 for temp_arg in temp_args:
   1313     temp_arg._detach()

File /usr/local/spark/python/pyspark/sql/utils.py:111, in capture_sql_exception.<locals>.deco(*a, **kw)
    109 def deco(*a, **kw):
    110     try:
--> 111         return f(*a, **kw)
    112     except py4j.protocol.Py4JJavaError as e:
    113         converted = convert_exception(e.java_exception)

File /usr/local/spark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o82.save.
: java.lang.NoSuchMethodError: 'scala.collection.immutable.ArraySeq scala.runtime.ScalaRunTime$.wrapRefArray(java.lang.Object[])'
	at io.pinecone.spark.pinecone.PineconeIndex.capabilities(PineconeIndex.scala:18)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Implicits$TableHelper.supports(DataSourceV2Implicits.scala:85)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:297)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by esadler-hbo** [comment]
For all the fools like me:

 I just asked ChatGPT and it said that the method was introduced in scala version 2.13. I was using 2.12. I needed to use this:

```python

spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .config('spark.jars.packages', 'io.pinecone:spark-pinecone_2.12:0.1.0') \. # DO NOT use 2.13 if your scala version is 2.12
    .getOrCreate()
```
