### ISSUE TITLE
Hitting Pinecone Upsert Rate Limit (50MB/s)

### ISSUE THREAD

**Issue by lugonthier** [pinecone-io/spark-pinecone#40]
- [x] I believe this is a new bug
- [x] I have searched the existing Github issues and Community Forum, and I could not find an existing post for this bug

**Describe the bug**
We are currently facing an issue with the Pinecone Spark connector when performing highly parallelized upserts to Pinecone. Specifically, we are hitting the Pinecone rate limit of 50 MB/second for upserts. Due to the nature of Spark jobs and their parallel execution, we end up exceeding this limit, causing upserts to fail or throttle, which negatively impacts the pipeline's performance.

**Error information**
If you have one, please include the full stack trace here. If not, please share as much as you can about the error.

```bash

24/10/20 15:13:54 WARN TaskSetManager: Lost task 42.0 in stage 1.0 (TID 43) (10.0.1.87 executor 4): shaded.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Request failed. You've reached the max upsert size limit per second for namespace default (50 MB per second). Pace your upserts or upgrade your plan.
	at shaded.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at shaded.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at shaded.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at io.pinecone.proto.VectorServiceGrpc$VectorServiceBlockingStub.upsert(VectorServiceGrpc.java:537)
	at io.pinecone.spark.pinecone.PineconeDataWriter.$anonfun$flushBatchToIndex$1(PineconeDataWriter.scala:138)
	at io.pinecone.spark.pinecone.PineconeDataWriter.$anonfun$flushBatchToIndex$1$adapted(PineconeDataWriter.scala:136)
	at scala.collection.mutable.HashMap$$anon$2.$anonfun$foreach$3(HashMap.scala:158)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:158)
	at io.pinecone.spark.pinecone.PineconeDataWriter.flushBatchToIndex(PineconeDataWriter.scala:136)
	at io.pinecone.spark.pinecone.PineconeDataWriter.write(PineconeDataWriter.scala:86)
	at io.pinecone.spark.pinecone.PineconeDataWriter.write(PineconeDataWriter.scala:13)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.write(WriteToDataSourceV2Exec.scala:493)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.$anonfun$run$1(WriteToDataSourceV2Exec.scala:448)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1398)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run(WriteToDataSourceV2Exec.scala:486)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run$(WriteToDataSourceV2Exec.scala:425)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:491)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:388)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
**Steps to reproduce the issue locally**
- Load from GCS
- Write to Pinecone

**Environment**
* Scala Version: 2.12
* Spark version: 3.5.1
* Spark Pinecone Connector version: 1.0.0

**Additional context**
About 500 M vectors.

**Comment by rohanshah18** [comment]
@lugonthier thanks for opening this issue, I have been informed that you're working with our Support team to resolve this.
